GET http://localhost:3001/

###
GET http://localhost:3001/tasks

###
POST http://localhost:3001/tasks
content-type: application/json

{
  "text": "Completar el Reto Nivel 3",
  "complete": false
}

###
PUT http://localhost:3001/tasks:id
content-type: application/json

{
  "id": 1,
  "text": "Completar el Reto Nivel 3",
  "complete": false
}

###
DELETE http://localhost:3001/tasks:id
content-type: application/json

{
  "id": 1
}